name: Деплой в Base Mainnet
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Установка зависимостей
        run: pip install web3 py-solc-x
      - name: Установка Solidity
        run: python -c "import solcx; solcx.install_solc('0.8.20')"
      - name: Деплой контракта
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        run: python deploy_helloworld.py
